### ISSUE TITLE
Gracefully handle configuration settings with an invalid content type

### ISSUE THREAD

**Issue by Tom-hayden** [tnc1997/azure-app-configuration-emulator#101]
**Describe the bug**

It is possible to add a kv with an incorrect content type from the UI. This causes any call to get the kv to return a 500.

**Current behavior**
 1. Navigate to the configuration explorer section. 
 2. Click Create
 3. Fill in the details with an incorrect content type
 4. Click create
 5. Refresh the page.
 6. You now cannot load any confguration.

**Expected behavior**
The key value should fail to create

**Comment by tnc1997** [comment]
Thank you very much for reporting this issue, I will aim to resolve it over the next few days.

**Comment by tnc1997** [comment]
After double checking the Azure Portal it looks like it is possible to add configuration settings with an invalid content type however doing so does not break the entire Azure App Configuration resource like it does to the emulator currently.
