### ISSUE TITLE
Front-end UI

### ISSUE THREAD

**Issue by paulirwin** [tnc1997/azure-app-configuration-emulator#43]
**Is your feature request related to a problem? Please describe.**
This is a proposal for adding a front-end UI to this project, to more easily manage configuration settings and feature flags with the local emulator.

**Describe the solution you'd like**
My current use case involves configuration settings being set in the Azure Portal UI in Configuration Explorer (or the Feature Flags view), including frequently changing their values to test them, so it is a bit burdensome to have to set these manually in the emulator via Postman and such. I'd love to have a front-end UI (probably accessible from the root URL of the app) so that I can easily toggle feature flags and configuration settings.

I think this could be done entirely in JS, with no server-side .NET code needed. It could have a credential/secret input that builds the authentication headers entirely client-side. This also could enable a future enhancement of specifying a target URL, to even use this against a live Azure App Config instance, to verify that it works properly, or even enable other potential use cases around having a local, debuggable remote configuration UI for Azure App Config, or enable sync from Azure App Config to your local emulator.

At a minimum, this should have all the basic Configuration Explorer functionality from the portal, such as creating/updating/deleting config settings with labels, as well as the Feature Manager functionality of creating/editing/deleting and toggling feature flags with labels. My use case also needs administration of feature flag filters (like the targeting filter), but I accept that that could be a separate future enhancement.

**Describe alternatives you've considered**
Postman, building an internal custom admin UI for my use case

**Additional context**
I have limited bandwidth at the moment but I could help get this initiative started, if that sounds good to @tnc1997. I would probably default to using the latest Angular/Material on this just because I know it like the back of my hand, but if someone else has different opinions on how it should be done, I can help contribute once they get the architecture started.

**Comment by tnc1997** [comment]
Hi @paulirwin, funnily enough the addition of a User Interface is something that I am actively looking at currently.

I don't have any updates to share at the moment, but I will use this issue to keep track of progress :smile:
