### ISSUE TITLE
Publish an official container image

### ISSUE THREAD

**Issue by goldsam** [tnc1997/azure-app-configuration-emulator#75]
My primary use case for you project is automated testing where my test environment is managed via [Testcontainers](https://github.com/testcontainers/testcontainers-dotnet). Unfortunately, this tool does not support (as far as I can tell) using a git URL for the container build context as your do in the docker-compose snippet of your `README.md`. For my use case, it would be valuable to reference an image in a OCI-complaint registry (such as github container registry).

If you endorse this effort, I would be happy to make create a PR which builds and publishes an image via github actions.

**Comment by goldsam** [comment]
Would you be willing open a `feat/75` branch for me to create a PR against?

**Comment by tnc1997** [comment]
Hi @goldsam, there are a few bits and pieces that I would like to complete first, such as the other open issues, then I will look to push an image to Docker Hub.

**Comment by tnc1997** [comment]
https://hub.docker.com/r/tnc1997/azure-app-configuration-emulator

**Comment by goldsam** [comment]
YAY!
