### ISSUE TITLE
Consider merging libraries to reduce complexity

### ISSUE THREAD

**Issue by goldsam** [tnc1997/azure-app-configuration-emulator#77]
I see that the project is made up of quite a few libraries which all get referenced by the main application. 
Many of these libraries:
   - are tiny - consisting of only 2 code files
   - do not encapsulate functionality reusable outside of the main application
 
You might consider collapsing some of these libraries into one or even into the main application. This would serve to: 
- condense the code in a more shallow and narrow directory structure possibly improving navigability and discoverability
- reduce the number of inter-project dependencies to achieve a simpler build process
- reduce startup time since fewer libraries would need loading and linking (though this is likely insignificant).

On that note, nice work on a great project! 😉 Cheers!

**Comment by tnc1997** [comment]
Hi @goldsam, thank you very much for your feedback, I am glad that you find this project useful!

Could I ask you to clone the branch `refactor/77` and let me know what you think of the changes?

**Comment by goldsam** [comment]
👍
