### ISSUE TITLE
Add support configuration auto-import on startup

### ISSUE THREAD

**Issue by goldsam** [tnc1997/azure-app-configuration-emulator#78]
It would be very convenient to be able to import configuration from a file on startup to facilitate testing. This would avoid the need to write custom code to seed the emulator with configuration prior to running my test cases.

**Comment by tnc1997** [comment]
Hi @goldsam, you may seed the database with configuration settings by mounting a database into the container.

**Comment by goldsam** [comment]
I instead opted to just initialize the configuration in the context of my test setup. My team uses [LightBDD](https://github.com/LightBDD/LightBDD), which has the added benefit of showing the configuration data in the test report. 

Although seeding the database is a bit more cumbersome that what I would have liked (had I pursued this approach), I suppose that would have worked.

**Comment by goldsam** [comment]
Mounting a databasse is inconvenient and cumbersome for a simple key-value store. It would ideal to define a simple JSON. format to handle this. I opted to handle this with a startup script.
